#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "hister"
name = "Hister"
description.en = "Your own search engine"
description.fr = "Votre propre moteur de recherche"

version = "0.18.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://hister.org/"
demo = "https://demo.hister.org/"
admindoc = "https://hister.org/docs/quickstart"
code = "https://github.com/asciimoo/hister"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    rename = "hister"
    in_subdir = false
    amd64.url = "https://github.com/asciimoo/hister/releases/download/v0.18.0/hister_0.18.0_linux_amd64"
    amd64.sha256 = "c9d7c0fbab4b7fe52b12f971e8e6a3e2e99b4b2642def03d6027dd4803f5c1aa"
    arm64.url = "https://github.com/asciimoo/hister/releases/download/v0.18.0/hister_0.18.0_linux_arm64"
    arm64.sha256 = "71f11f4c711fcc4ecd2dc320545d12cafccd7d5f33734686cf1d85ba56fbc902"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^hister_.*_linux_amd64$"
    autoupdate.asset.arm64 = "^hister_.*_linux_arm64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
