#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "hister"
name = "Hister"
description.en = "Your own search engine"
description.fr = "Votre propre moteur de recherche"

version = "0.19.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://hister.org/"
demo = "https://demo.hister.org/"
admindoc = "https://hister.org/docs/quickstart"
code = "https://github.com/asciimoo/hister"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    rename = "hister"
    in_subdir = false
    amd64.url = "https://github.com/asciimoo/hister/releases/download/v0.19.0/hister_0.19.0_linux_amd64"
    amd64.sha256 = "7571f7b94039917d519372fa6aff18fe12c2ef50f981ac847ec1aff4d7e41701"
    arm64.url = "https://github.com/asciimoo/hister/releases/download/v0.19.0/hister_0.19.0_linux_arm64"
    arm64.sha256 = "2e20d119a0cda82c0fdd0d8798a4f574301f2a8507c88b1fc288b008c388e4a5"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^hister_.*_linux_amd64$"
    autoupdate.asset.arm64 = "^hister_.*_linux_arm64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
