#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "hister"
name = "Hister"
description.en = "Your own search engine"
description.fr = "Votre propre moteur de recherche"

version = "0.20.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://hister.org/"
demo = "https://demo.hister.org/"
admindoc = "https://hister.org/docs/quickstart"
code = "https://github.com/asciimoo/hister"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    rename = "hister"
    in_subdir = false
    amd64.url = "https://github.com/asciimoo/hister/releases/download/v0.20.0/hister_0.20.0_linux_amd64"
    amd64.sha256 = "28c453cd3fe383dac936f91450c0bd6d3be4944079670aa607f38e01215844fe"
    arm64.url = "https://github.com/asciimoo/hister/releases/download/v0.20.0/hister_0.20.0_linux_arm64"
    arm64.sha256 = "606a8f3e4364b37b3861581a111d8acda58f38357afad0ae0ceba67978a8899a"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^hister_.*_linux_amd64$"
    autoupdate.asset.arm64 = "^hister_.*_linux_arm64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
